COMPANY_NAME: 'HIGH CARE AUTOMOBILES'
COMPANY_TITLE: 'Vehicle Solution for ALL BRANDS'
COMPANY_ADDRESS: 'Tejgoan I/A, Dhaka-1208, Bangladesh'
COMPANY_TNT_PHONE: '02-8891515'
COMPANY_MOBILE: '01775246164, 01960001403, 01689762515'
COMPANY_EMAIL: 'highcareautomobiles@gmail.com'